### Teste Cria Competição 100m rasos
POST http://localhost:3000/competition/create
Content-Type: application/json

{
    "name": "100m Rasos de Montreal",
    "modality": "100M RASOS"
}

### Teste Cria Competição 100m rasos
POST http://localhost:3000/competition/create
Content-Type: application/json

{
    "name": "100m Rasos do Japão",
    "modality": "100M RASOS"
}

#### Teste Cria competição dardos
POST http://localhost:3000/competition/create
Content-Type: application/json

{
    "name": "Lançamento de dardos da Mongólia",
    "modality": "LANÇAMENTO DE DARDOS"
}

### Inserir um atleta e seu tempo numa competição de 100m rasos
# @id = f41a78e7-1c9a-4d62-9053-b8b2b4bd1910
POST http://localhost:3000/competition/meter/{{id}}
Content-Type: application/json

{
    "athlete": "Magnolia Johnson",
    "time": "10.58"
}

### Inserir outra pessoa em uma competição de 100m rasos
# @id = f41a78e7-1c9a-4d62-9053-b8b2b4bd1910
POST http://localhost:3000/competition/meter/{{id}}
Content-Type: application/json

{
    "athlete": "Isadora Theodore",
    "time": "10.60"
}

### Inserir outra pessoa em uma competição de 100m rasos
# @id = f41a78e7-1c9a-4d62-9053-b8b2b4bd1910
POST http://localhost:3000/meterDash/{{id}}
Content-Type: application/json

{
    "athlete": "Thelma Rush",
    "time": "10.623"
}

### Inserir um atleta e seu tempo numa competição de 100m rasos
# @id = f41a78e7-1c9a-4d62-9053-b8b2b4bd1910
POST http://localhost:3000/competition/meter/{{id}}
Content-Type: application/json

{
    "athlete": "Evelyn Mathew",
    "time": "10.61"
}
### Inserir um atleta e seu tempo numa competição de 100m rasos
# @id = de0e37c0-a3ed-4a79-b50f-969094843f36
POST http://localhost:3000/meterDash/{{id}}
Content-Type: application/json

{
    "athlete": "Anna Schevshenko",
    "time": "10.58"
}

### Inserir um atleta e seu resultado numa competição de lançamewnto de dardos
# @id = 8ce43825-6a23-495f-bba6-db2ae187cb6e
POST http://localhost:3000/javelinThrow/{{id}}
Content-Type: application/json

{
    "athlete": "Anna Schevshenko",
    "distance": "45.64"
}

### Inserir mais um atleta e seu resultado numa competição de lançamewnto de dardos
@id = 8ce43825-6a23-495f-bba6-db2ae187cb6e
POST http://localhost:3000/javelinThrow/{{id}}
Content-Type: application/json

{
    "athlete": "Evelyn Mathew",
    "distance": "45.645"
}

### Inserir mais um atleta e seu resultado numa competição de lançamewnto de dardos
@id = 8ce43825-6a23-495f-bba6-db2ae187cb6e
POST http://localhost:3000/javelinThrow/{{id}}
Content-Type: application/json

{
    "athlete": "Thelma Rush",
    "distance": "44.218"
}

### Encerra competição
PUT http://localhost:3000/competition/end
Content-Type: application/json

{
    "id": "de0e37c0-a3ed-4a79-b50f-969094843f36"
}

### Ranking de 100m Rasos
# @id = f41a78e7-1c9a-4d62-9053-b8b2b4bd1910
get http://localhost:3000/competition/rankings/{{id}}

### Ranking de lançamento de dardos
@id = 8ce43825-6a23-495f-bba6-db2ae187cb6e
get http://localhost:3000/competition/rankings/{{id}}