# @name signup

POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Norman Osbourne", 
   "nickname": "Green Goblin", 
   "email": "osbourne@oscorp.com" ,
   "password": "ihatepeter"
}

###

POST http://localhost:3003/user/login
Content-Type: application/json

{ 
   "email": "osbourne@oscorp.com" ,
   "password": "ihatepeter"
}

###

GET http://localhost:3003/user/profile
Content-Type: application/json

headers:{ "Authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDU1Nzk2MjAsImV4cCI6MTY0NTU3OTc0MH0.nR1RM8PQHtYX29Er8fAoki4ywkW2DV6wl97V8ndi2rc" }

###

@id = {{signup.response.body.newUser.id}}

PUT http://localhost:3003/user/edit/{{id}}
Content-Type: application/json

{
   "name": "Harry Osbourne" 
}