POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "astrodev",
    "email": "astrodev@amil.com",
    "password": "123456"
}

###

GET http://localhost:3003/users

###

POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "MacBook Air",
    "price": 5000.00,
    "image_url": "https://i.picsum.photos/id/0/5616/3744.jpg?hmac=3GAAioiQziMGEtLbfrdbcoenXoWAW-zlyEAMkfEdBzQ"
}

###

POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "AMD Ryzen 5600x",
    "price": "",
    "image_url": "https://www.amd.com/system/files/styles/600px/private/2020-09/616656-amd-ryzen-5-5000-series-PIB-fan-1260x709.png?itok=JV2LS8dj"
}

###

GET http://localhost:3003/products
